[project]
name = "app"
version = "0.1.3"
description = "A typed solution to quickly create websites"
readme = "README.md"
requires-python = ">=3.9"
license = {text = "BSD"}
dependencies = [
    "typed @ git+https://github.com/pythonalta/typed",
    "utils @ git+https://github.com/pythonalta/typed",
    "fastapi",
    "markdown",
    "pyyaml",
    "beautifulsoup4"
]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["app*"]           
